{% set version = '2.30-0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lsmeans
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lsmeans_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lsmeans/lsmeans_{{ version }}.tar.gz
  sha256: aef4c2fe4cb292edac79e83f50feac83429f6d7d50fe1780980eacf8dc6f65fc

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-emmeans >=1.3
  run:
    - r-base
    - r-emmeans >=1.3

test:
  commands:
    - $R -e "library('lsmeans')"           # [not win]
    - "\"%R%\" -e \"library('lsmeans')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lsmeans
  license: GPL-2 | GPL-3
  summary: 'Obtain least-squares means for linear, generalized linear,  and mixed models. Compute
    contrasts or linear functions of  least-squares means, and comparisons of slopes.  Plots
    and compact letter displays. Least-squares means were proposed in Harvey, W (1960)
    "Least-squares analysis of data with unequal subclass numbers", Tech Report ARS-20-8,
    USDA National Agricultural Library, and discussed further in Searle, Speed, and
    Milliken (1980) "Population marginal means  in the linear model: An alternative
    to least squares means",  The American Statistician 34(4), 216-221 <doi:10.1080/00031305.1980.10483031>.
    NOTE: lsmeans now relies primarily on code in the ''emmeans'' package. ''lsmeans''
    will be archived in the near future.'
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lsmeans
# Type: Package
# Title: Least-Squares Means
# Version: 2.30-0
# Date: 2018-11-02
# Authors@R: c(person("Russell", "Lenth", role = c("aut", "cre", "cph"),  email = "russell-lenth@uiowa.edu"))
# Depends: emmeans (>= 1.3), methods, R (>= 3.2)
# Suggests:
# ByteCompile: yes
# Description: Obtain least-squares means for linear, generalized linear,  and mixed models. Compute contrasts or linear functions of  least-squares means, and comparisons of slopes.  Plots and compact letter displays. Least-squares means were proposed in Harvey, W (1960) "Least-squares analysis of data with unequal subclass numbers", Tech Report ARS-20-8, USDA National Agricultural Library, and discussed further in Searle, Speed, and Milliken (1980) "Population marginal means  in the linear model: An alternative to least squares means",  The American Statistician 34(4), 216-221 <doi:10.1080/00031305.1980.10483031>. NOTE: lsmeans now relies primarily on code in the 'emmeans' package. 'lsmeans' will be archived in the near future.
# License: GPL-2 | GPL-3
# NeedsCompilation: no
# Packaged: 2018-11-02 19:06:49 UTC; rlenth
# Author: Russell Lenth [aut, cre, cph]
# Maintainer: Russell Lenth <russell-lenth@uiowa.edu>
# Repository: CRAN
# Date/Publication: 2018-11-02 23:50:11 UTC
