{% set version = '2.27-62' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lsmeans
  version: {{ version|replace("-", "_") }}

source:
  fn: lsmeans_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lsmeans_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lsmeans/lsmeans_{{ version }}.tar.gz
  sha256: ffccf0235854a7cae477c1141e678e64f300fe2a4a0d0545c648aa8a66a369b5

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-coda >=0.17
    - r-estimability
    - r-multcomp
    - r-mvtnorm
    - r-nlme
    - r-plyr
    - r-xtable >=1.8_2

  run:
    - r-base
    - r-coda >=0.17
    - r-estimability
    - r-multcomp
    - r-mvtnorm
    - r-nlme
    - r-plyr
    - r-xtable >=1.8_2

test:
  commands:
    - $R -e "library('lsmeans')"  # [not win]
    - "\"%R%\" -e \"library('lsmeans')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lsmeans
  license: GPL (>= 2)
  summary: Obtain least-squares means for many linear, generalized linear,  and mixed models.
    Compute contrasts or linear functions of least-squares means, and comparisons of
    slopes. Plots and compact letter displays.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
