appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: lKDdfOo2tW/xsw8qAe8bUCE9TEV+cSbN1UV66suFX4D5yZx9tNB08rt8EDzLuK9C+gb8a2GtokXWR0K11HK52cOMviaqOmyv0vrmXisJVvBR0FQhJhZZTNx/ff9YoziZlE1jOt5AhfDXWLFNCTjYRtw6Sfti7JxhnnRiJv1lHavoFToJ7fnC4r1botmpyxFPOVW2DjLN8oXCOa7LHbu8K8TBFCOJCpxIBQMXFzyIJVEg21aCiys8nz/hI5sdtD4fG1sGxYcD34272gia5FpV78rU3POAwe6Ssclj009YtjRL0K0bYjLoaKw0y7uLVOzK9sSJD828pmu7sK1rZpwOYWMZO7fSLB4iAb5WEDjHabfoJefYoVVUGg8Dnn0p8gwq5j3cqNOD6GauWVjTnERr55i4XYmlJltCXobAyODStkdqR9/EiJglKSgF9H21oxbdQJ0t1lkO7ZWyCY+3CoN71jgzDlM6ZLXJp7icZM+SJfoF5Z3RK6oadrup+itx0iAtCLvuKHr7MIJBcRdrotty1hzE89j2dwY3HHqFlwa9c5R14U5l9W1j0HZBzdrWe+Y1r2QzhBmEhAzgwjQ6TliHvhlgwCxzWk+JVrHrDl9QS2Q/9BRkoAjd4aExjyWWwGjwxAWiwqhfcECaj8Yfc+ryx4pKE9rjjUVR9+bLXUK637A=}
